services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    KonradMichalik\Typo3DumpServer\:
        resource: '../Classes/*'
        exclude: '../Classes/Domain/Model/*'

    KonradMichalik\Typo3DumpServer\Command\DumpServerCommand:
        tags:
            -   name: console.command
                command: 'server:dump'
                description: 'Start a Symfony Var Dump server that collects and displays `dump` outputs in a single place for debugging your application.'
